name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy with '...'
        2. Upload package '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the package repository?
      options:
        - Docker Compose
        - Kubernetes (manifests)
        - Helm Chart
        - Terraform (AWS)
        - Terraform (GCP)
        - Terraform (Azure)
        - Terraform (DigitalOcean)
        - Terraform (Vultr)
        - Other
    validations:
      required: true

  - type: dropdown
    id: package-type
    attributes:
      label: Package Type
      description: Which package type is affected? (if applicable)
      options:
        - DEB (Debian/Ubuntu)
        - RPM (RHEL/Fedora/Rocky)
        - Arch Linux
        - Alpine Linux
        - All types
        - Not applicable
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: "e.g., v1.0.0 or commit SHA"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - OS (e.g., Ubuntu 22.04, macOS 14)
        - Docker version (if applicable)
        - Kubernetes version (if applicable)
        - Architecture (amd64/arm64)
      placeholder: |
        - OS: Ubuntu 22.04
        - Docker: 24.0.5
        - Architecture: amd64
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have included all relevant information above
          required: true
